// NOTE: This is generated by 'w3 codegen', DO NOT MODIFY

// @ts-noCheck
import {
  UInt,
  UInt8,
  UInt16,
  UInt32,
  Int,
  Int8,
  Int16,
  Int32,
  Bytes,
  BigInt,
  Json,
  String,
  Boolean
} from "../baseTypes";
import {
  TxReceipt,
  TxResponse,
  TxRequest,
  TxOverrides,
  StaticTxResult,
  Log,
  EventNotification,
  Access,
  Connection,
  Network,
} from "./types";
import { ExtensionInvocation } from "@web3api/core-js";

export interface Input_callContractView extends Record<string, unknown> {
  address: String;
  method: String;
  args?: Array<String> | null;
  connection?: Connection | null;
}

export interface Input_callContractStatic extends Record<string, unknown> {
  address: String;
  method: String;
  args?: Array<String> | null;
  connection?: Connection | null;
  txOverrides?: TxOverrides | null;
}

export interface Input_encodeParams extends Record<string, unknown> {
  types: Array<String>;
  values: Array<String>;
}

export interface Input_encodeFunction extends Record<string, unknown> {
  method: String;
  args?: Array<String> | null;
}

export interface Input_getSignerAddress extends Record<string, unknown> {
  connection?: Connection | null;
}

export interface Input_getSignerBalance extends Record<string, unknown> {
  blockTag?: BigInt | null;
  connection?: Connection | null;
}

export interface Input_getSignerTransactionCount extends Record<string, unknown> {
  blockTag?: BigInt | null;
  connection?: Connection | null;
}

export interface Input_getGasPrice extends Record<string, unknown> {
  connection?: Connection | null;
}

export interface Input_estimateTransactionGas extends Record<string, unknown> {
  tx: TxRequest;
  connection?: Connection | null;
}

export interface Input_estimateContractCallGas extends Record<string, unknown> {
  address: String;
  method: String;
  args?: Array<String> | null;
  connection?: Connection | null;
  txOverrides?: TxOverrides | null;
}

export interface Input_checkAddress extends Record<string, unknown> {
  address: String;
}

export interface Input_toWei extends Record<string, unknown> {
  eth: String;
}

export interface Input_toEth extends Record<string, unknown> {
  wei: BigInt;
}

export interface Input_awaitTransaction extends Record<string, unknown> {
  txHash: String;
  confirmations: UInt32;
  timeout: UInt32;
  connection?: Connection | null;
}

export interface Input_waitForEvent extends Record<string, unknown> {
  address: String;
  event: String;
  args?: Array<String> | null;
  timeout?: UInt32 | null;
  connection?: Connection | null;
}

export interface Input_getNetwork extends Record<string, unknown> {
  connection?: Connection | null;
}

export interface EthereumQueryModule {
  callContractView(input: Input_callContractView): ExtensionInvocation<String>;
  callContractStatic(input: Input_callContractStatic): ExtensionInvocation<StaticTxResult>;
  encodeParams(input: Input_encodeParams): ExtensionInvocation<String>;
  encodeFunction(input: Input_encodeFunction): ExtensionInvocation<String>;
  getSignerAddress(input: Input_getSignerAddress): ExtensionInvocation<String>;
  getSignerBalance(input: Input_getSignerBalance): ExtensionInvocation<BigInt>;
  getSignerTransactionCount(input: Input_getSignerTransactionCount): ExtensionInvocation<BigInt>;
  getGasPrice(input: Input_getGasPrice): ExtensionInvocation<BigInt>;
  estimateTransactionGas(input: Input_estimateTransactionGas): ExtensionInvocation<BigInt>;
  estimateContractCallGas(input: Input_estimateContractCallGas): ExtensionInvocation<BigInt>;
  checkAddress(input: Input_checkAddress): ExtensionInvocation<Boolean>;
  toWei(input: Input_toWei): ExtensionInvocation<BigInt>;
  toEth(input: Input_toEth): ExtensionInvocation<String>;
  awaitTransaction(input: Input_awaitTransaction): ExtensionInvocation<TxReceipt>;
  waitForEvent(input: Input_waitForEvent): ExtensionInvocation<EventNotification>;
  getNetwork(input: Input_getNetwork): ExtensionInvocation<Network>;
}

