// NOTE: This is generated by 'w3 codegen', DO NOT MODIFY

import "@web3api/client-js/build/Web3ApiClient";
import { IEthereumExtension } from "./classExtension";

declare module "@web3api/client-js/build/Web3ApiClient" {
  export interface Web3ApiClient {
    ethereum: IEthereumExtension;
  }
}
