import {
  FACTORY_ADDRESS as UNI_FACTORY_ADDRESS,
  POOL_INIT_CODE_HASH as UNI_POOL_INIT_CODE_HASH,
  POOL_INIT_CODE_HASH_OPTIMISM as UNI_POOL_INIT_CODE_HASH_OPTIMISM,
  POOL_INIT_CODE_HASH_OPTIMISM_KOVAN as UNI_POOL_INIT_CODE_HASH_OPTIMISM_KOVAN,
} from "../utils/constants";

export const FACTORY_ADDRESS = (): string => UNI_FACTORY_ADDRESS;

export const POOL_INIT_CODE_HASH = (): string => UNI_POOL_INIT_CODE_HASH;

export const POOL_INIT_CODE_HASH_OPTIMISM = (): string =>
  UNI_POOL_INIT_CODE_HASH_OPTIMISM;

export const POOL_INIT_CODE_HASH_OPTIMISM_KOVAN = (): string =>
  UNI_POOL_INIT_CODE_HASH_OPTIMISM_KOVAN;
