// NOTE: This is generated by 'w3 codegen', DO NOT MODIFY

// @ts-noCheck
import {
  UInt,
  UInt8,
  UInt16,
  UInt32,
  Int,
  Int8,
  Int16,
  Int32,
  Bytes,
  BigInt,
  Json,
  String,
  Boolean
} from "../baseTypes";
import {
  SwapArgs,
  Currency,
  Token,
  Route,
  Tick,
  TickListDataProvider,
  Pool,
  Trade,
  TokenAmount,
  TradeSwap,
  Price,
  SwapOptions,
  PermitOptions,
  FeeOptions,
  MethodParameters,
  GasOptions,
  NextTickResult,
  PoolChangeResult,
  TradeRoute,
  IncentiveKey,
  ClaimOptions,
  FullWithdrawOptions,
  QuoteOptions,
  CommonAddLiquidityOptions,
  AddLiquidityOptions,
  SafeTransferOptions,
  CollectOptions,
  NFTPermitOptions,
  RemoveLiquidityOptions,
  BestTradeOptions,
  Position,
  MintAmounts,
  ChainIdEnum,
  ChainIdString,
  ChainId,
  FeeAmountEnum,
  FeeAmountString,
  FeeAmount,
  TradeTypeEnum,
  TradeTypeString,
  TradeType,
  PermitVEnum,
  PermitVString,
  PermitV,
  RoundingEnum,
  RoundingString,
  Rounding,
  Ethereum_Connection,
  Ethereum_TxOverrides,
  Ethereum_TxResponse,
  Ethereum_Access,
  Ethereum_TxReceipt,
  Ethereum_Log,
  Ethereum_TxRequest,
  Ethereum_StaticTxResult,
  Ethereum_EventNotification,
  Ethereum_Network,
  ERC20_Ethereum_Connection,
  Ethereum_Mutation,
  Ethereum_Query,
  SHA3_Query,
  EthersSolidity_Query,
  ERC20_Query,
  Subgraph_Query,
} from "./types";
import * as MutationInputs from "./mutation";
import * as QueryInputs from "./query";
import { Client, Uri, ExtensionInvocation, Extension, ExtensionConfig, ExtensionFactory, InvokeApiOptions } from "@web3api/core-js";

export interface UniswapExtensionConfig extends ExtensionConfig {}

export interface IUniswapExtension extends Extension, MutationInputs.UniswapMutationModule, QueryInputs.UniswapQueryModule {}

class UniswapExtension implements IUniswapExtension {

  private client: Client;
  readonly uri: Uri;
  readonly config: UniswapExtensionConfig;

  constructor(client: Client, config: UniswapExtensionConfig) {
    this.client = client;
    if (config?.uri) {
      if (typeof config.uri === "string") {
        this.uri = new Uri(config.uri);
      } else {
        this.uri = config.uri as Uri;
      }
    } else {
      this.uri = new Uri("w3://fs//Users/kris/WebstormProjects/integrations/uniswapv3/wrapper/build");
    }
    this.config = config;
  }

  placeholder(
    input: MutationInputs.Input_placeholder,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "mutation",
      method: "placeholder",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  currencyEquals(
    input: QueryInputs.Input_currencyEquals,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "currencyEquals",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  tokenEquals(
    input: QueryInputs.Input_tokenEquals,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tokenEquals",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  tokenAmountEquals(
    input: QueryInputs.Input_tokenAmountEquals,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tokenAmountEquals",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  tokenSortsBefore(
    input: QueryInputs.Input_tokenSortsBefore,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tokenSortsBefore",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  getEther(
    input: QueryInputs.Input_getEther,
  ): ExtensionInvocation<Token> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getEther",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Token>(options),
    };
  }

  getWETH(
    input: QueryInputs.Input_getWETH,
  ): ExtensionInvocation<Token> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getWETH",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Token>(options),
    };
  }

  isEther(
    input: QueryInputs.Input_isEther,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "isEther",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  wrapToken(
    input: QueryInputs.Input_wrapToken,
  ): ExtensionInvocation<Token> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "wrapToken",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Token>(options),
    };
  }

  wrapAmount(
    input: QueryInputs.Input_wrapAmount,
  ): ExtensionInvocation<TokenAmount> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "wrapAmount",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<TokenAmount>(options),
    };
  }

  createTickListDataProvider(
    input: QueryInputs.Input_createTickListDataProvider,
  ): ExtensionInvocation<TickListDataProvider> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createTickListDataProvider",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<TickListDataProvider>(options),
    };
  }

  getTick(
    input: QueryInputs.Input_getTick,
  ): ExtensionInvocation<Tick> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getTick",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Tick>(options),
    };
  }

  nextInitializedTickWithinOneWord(
    input: QueryInputs.Input_nextInitializedTickWithinOneWord,
  ): ExtensionInvocation<NextTickResult> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "nextInitializedTickWithinOneWord",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<NextTickResult>(options),
    };
  }

  createPool(
    input: QueryInputs.Input_createPool,
  ): ExtensionInvocation<Pool> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createPool",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Pool>(options),
    };
  }

  getPoolAddress(
    input: QueryInputs.Input_getPoolAddress,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getPoolAddress",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  poolInvolvesToken(
    input: QueryInputs.Input_poolInvolvesToken,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "poolInvolvesToken",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  poolToken0Price(
    input: QueryInputs.Input_poolToken0Price,
  ): ExtensionInvocation<Price> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "poolToken0Price",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Price>(options),
    };
  }

  poolToken1Price(
    input: QueryInputs.Input_poolToken1Price,
  ): ExtensionInvocation<Price> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "poolToken1Price",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Price>(options),
    };
  }

  poolPriceOf(
    input: QueryInputs.Input_poolPriceOf,
  ): ExtensionInvocation<Price> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "poolPriceOf",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Price>(options),
    };
  }

  poolChainId(
    input: QueryInputs.Input_poolChainId,
  ): ExtensionInvocation<ChainId> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "poolChainId",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<ChainId>(options),
    };
  }

  getPoolOutputAmount(
    input: QueryInputs.Input_getPoolOutputAmount,
  ): ExtensionInvocation<PoolChangeResult> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getPoolOutputAmount",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<PoolChangeResult>(options),
    };
  }

  getPoolInputAmount(
    input: QueryInputs.Input_getPoolInputAmount,
  ): ExtensionInvocation<PoolChangeResult> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getPoolInputAmount",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<PoolChangeResult>(options),
    };
  }

  getPoolTickSpacing(
    input: QueryInputs.Input_getPoolTickSpacing,
  ): ExtensionInvocation<Int32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getPoolTickSpacing",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Int32>(options),
    };
  }

  createRoute(
    input: QueryInputs.Input_createRoute,
  ): ExtensionInvocation<Route> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createRoute",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Route>(options),
    };
  }

  routeChainId(
    input: QueryInputs.Input_routeChainId,
  ): ExtensionInvocation<ChainId> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "routeChainId",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<ChainId>(options),
    };
  }

  routeMidPrice(
    input: QueryInputs.Input_routeMidPrice,
  ): ExtensionInvocation<Price> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "routeMidPrice",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Price>(options),
    };
  }

  createTradeExactIn(
    input: QueryInputs.Input_createTradeExactIn,
  ): ExtensionInvocation<Trade> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createTradeExactIn",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Trade>(options),
    };
  }

  createTradeExactOut(
    input: QueryInputs.Input_createTradeExactOut,
  ): ExtensionInvocation<Trade> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createTradeExactOut",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Trade>(options),
    };
  }

  createTradeFromRoute(
    input: QueryInputs.Input_createTradeFromRoute,
  ): ExtensionInvocation<Trade> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createTradeFromRoute",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Trade>(options),
    };
  }

  createTradeFromRoutes(
    input: QueryInputs.Input_createTradeFromRoutes,
  ): ExtensionInvocation<Trade> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createTradeFromRoutes",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Trade>(options),
    };
  }

  createUncheckedTrade(
    input: QueryInputs.Input_createUncheckedTrade,
  ): ExtensionInvocation<Trade> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createUncheckedTrade",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Trade>(options),
    };
  }

  createUncheckedTradeWithMultipleRoutes(
    input: QueryInputs.Input_createUncheckedTradeWithMultipleRoutes,
  ): ExtensionInvocation<Trade> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createUncheckedTradeWithMultipleRoutes",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Trade>(options),
    };
  }

  tradeInputAmount(
    input: QueryInputs.Input_tradeInputAmount,
  ): ExtensionInvocation<TokenAmount> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tradeInputAmount",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<TokenAmount>(options),
    };
  }

  tradeOutputAmount(
    input: QueryInputs.Input_tradeOutputAmount,
  ): ExtensionInvocation<TokenAmount> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tradeOutputAmount",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<TokenAmount>(options),
    };
  }

  tradeExecutionPrice(
    input: QueryInputs.Input_tradeExecutionPrice,
  ): ExtensionInvocation<Price> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tradeExecutionPrice",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Price>(options),
    };
  }

  tradePriceImpact(
    input: QueryInputs.Input_tradePriceImpact,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tradePriceImpact",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  tradeMinimumAmountOut(
    input: QueryInputs.Input_tradeMinimumAmountOut,
  ): ExtensionInvocation<TokenAmount> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tradeMinimumAmountOut",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<TokenAmount>(options),
    };
  }

  tradeMaximumAmountIn(
    input: QueryInputs.Input_tradeMaximumAmountIn,
  ): ExtensionInvocation<TokenAmount> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tradeMaximumAmountIn",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<TokenAmount>(options),
    };
  }

  tradeWorstExecutionPrice(
    input: QueryInputs.Input_tradeWorstExecutionPrice,
  ): ExtensionInvocation<Price> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tradeWorstExecutionPrice",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Price>(options),
    };
  }

  bestTradeExactIn(
    input: QueryInputs.Input_bestTradeExactIn,
  ): ExtensionInvocation<Array<Trade>> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "bestTradeExactIn",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Array<Trade>>(options),
    };
  }

  bestTradeExactOut(
    input: QueryInputs.Input_bestTradeExactOut,
  ): ExtensionInvocation<Array<Trade>> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "bestTradeExactOut",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Array<Trade>>(options),
    };
  }

  createPosition(
    input: QueryInputs.Input_createPosition,
  ): ExtensionInvocation<Position> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createPosition",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Position>(options),
    };
  }

  createPositionFromAmounts(
    input: QueryInputs.Input_createPositionFromAmounts,
  ): ExtensionInvocation<Position> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createPositionFromAmounts",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Position>(options),
    };
  }

  createPositionFromAmount0(
    input: QueryInputs.Input_createPositionFromAmount0,
  ): ExtensionInvocation<Position> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createPositionFromAmount0",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Position>(options),
    };
  }

  createPositionFromAmount1(
    input: QueryInputs.Input_createPositionFromAmount1,
  ): ExtensionInvocation<Position> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createPositionFromAmount1",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Position>(options),
    };
  }

  positionToken0PriceLower(
    input: QueryInputs.Input_positionToken0PriceLower,
  ): ExtensionInvocation<Price> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "positionToken0PriceLower",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Price>(options),
    };
  }

  positionToken0PriceUpper(
    input: QueryInputs.Input_positionToken0PriceUpper,
  ): ExtensionInvocation<Price> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "positionToken0PriceUpper",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Price>(options),
    };
  }

  positionAmount0(
    input: QueryInputs.Input_positionAmount0,
  ): ExtensionInvocation<TokenAmount> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "positionAmount0",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<TokenAmount>(options),
    };
  }

  positionAmount1(
    input: QueryInputs.Input_positionAmount1,
  ): ExtensionInvocation<TokenAmount> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "positionAmount1",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<TokenAmount>(options),
    };
  }

  mintAmounts(
    input: QueryInputs.Input_mintAmounts,
  ): ExtensionInvocation<MintAmounts> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "mintAmounts",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MintAmounts>(options),
    };
  }

  mintAmountsWithSlippage(
    input: QueryInputs.Input_mintAmountsWithSlippage,
  ): ExtensionInvocation<MintAmounts> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "mintAmountsWithSlippage",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MintAmounts>(options),
    };
  }

  burnAmountsWithSlippage(
    input: QueryInputs.Input_burnAmountsWithSlippage,
  ): ExtensionInvocation<MintAmounts> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "burnAmountsWithSlippage",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MintAmounts>(options),
    };
  }

  swapCallParameters(
    input: QueryInputs.Input_swapCallParameters,
  ): ExtensionInvocation<MethodParameters> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "swapCallParameters",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MethodParameters>(options),
    };
  }

  encodeRouteToPath(
    input: QueryInputs.Input_encodeRouteToPath,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "encodeRouteToPath",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  encodePermit(
    input: QueryInputs.Input_encodePermit,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "encodePermit",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  encodeUnwrapWETH9(
    input: QueryInputs.Input_encodeUnwrapWETH9,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "encodeUnwrapWETH9",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  encodeSweepToken(
    input: QueryInputs.Input_encodeSweepToken,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "encodeSweepToken",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  encodeRefundETH(
    input: QueryInputs.Input_encodeRefundETH,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "encodeRefundETH",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  encodeMulticall(
    input: QueryInputs.Input_encodeMulticall,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "encodeMulticall",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  collectRewards(
    input: QueryInputs.Input_collectRewards,
  ): ExtensionInvocation<MethodParameters> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "collectRewards",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MethodParameters>(options),
    };
  }

  withdrawToken(
    input: QueryInputs.Input_withdrawToken,
  ): ExtensionInvocation<MethodParameters> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "withdrawToken",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MethodParameters>(options),
    };
  }

  encodeDeposit(
    input: QueryInputs.Input_encodeDeposit,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "encodeDeposit",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  quoteCallParameters(
    input: QueryInputs.Input_quoteCallParameters,
  ): ExtensionInvocation<MethodParameters> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "quoteCallParameters",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MethodParameters>(options),
    };
  }

  createCallParameters(
    input: QueryInputs.Input_createCallParameters,
  ): ExtensionInvocation<MethodParameters> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "createCallParameters",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MethodParameters>(options),
    };
  }

  addCallParameters(
    input: QueryInputs.Input_addCallParameters,
  ): ExtensionInvocation<MethodParameters> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "addCallParameters",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MethodParameters>(options),
    };
  }

  collectCallParameters(
    input: QueryInputs.Input_collectCallParameters,
  ): ExtensionInvocation<MethodParameters> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "collectCallParameters",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MethodParameters>(options),
    };
  }

  removeCallParameters(
    input: QueryInputs.Input_removeCallParameters,
  ): ExtensionInvocation<MethodParameters> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "removeCallParameters",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MethodParameters>(options),
    };
  }

  safeTransferFromParameters(
    input: QueryInputs.Input_safeTransferFromParameters,
  ): ExtensionInvocation<MethodParameters> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "safeTransferFromParameters",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<MethodParameters>(options),
    };
  }

  toHex(
    input: QueryInputs.Input_toHex,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "toHex",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  computePoolAddress(
    input: QueryInputs.Input_computePoolAddress,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "computePoolAddress",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  encodeSqrtRatioX96(
    input: QueryInputs.Input_encodeSqrtRatioX96,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "encodeSqrtRatioX96",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  mulDivRoundingUp(
    input: QueryInputs.Input_mulDivRoundingUp,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "mulDivRoundingUp",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  addDelta(
    input: QueryInputs.Input_addDelta,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "addDelta",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  maxLiquidityForAmounts(
    input: QueryInputs.Input_maxLiquidityForAmounts,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "maxLiquidityForAmounts",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  mostSignificantBit(
    input: QueryInputs.Input_mostSignificantBit,
  ): ExtensionInvocation<UInt32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "mostSignificantBit",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<UInt32>(options),
    };
  }

  nearestUsableTick(
    input: QueryInputs.Input_nearestUsableTick,
  ): ExtensionInvocation<Int32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "nearestUsableTick",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Int32>(options),
    };
  }

  tickToPrice(
    input: QueryInputs.Input_tickToPrice,
  ): ExtensionInvocation<Price> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tickToPrice",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Price>(options),
    };
  }

  priceToClosestTick(
    input: QueryInputs.Input_priceToClosestTick,
  ): ExtensionInvocation<Int32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "priceToClosestTick",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Int32>(options),
    };
  }

  getAmount0Delta(
    input: QueryInputs.Input_getAmount0Delta,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getAmount0Delta",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  getAmount1Delta(
    input: QueryInputs.Input_getAmount1Delta,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getAmount1Delta",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  getNextSqrtPriceFromInput(
    input: QueryInputs.Input_getNextSqrtPriceFromInput,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getNextSqrtPriceFromInput",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  getNextSqrtPriceFromOutput(
    input: QueryInputs.Input_getNextSqrtPriceFromOutput,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getNextSqrtPriceFromOutput",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  validateTickList(
    input: QueryInputs.Input_validateTickList,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "validateTickList",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  tickIsBelowSmallest(
    input: QueryInputs.Input_tickIsBelowSmallest,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tickIsBelowSmallest",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  tickIsAtOrAboveLargest(
    input: QueryInputs.Input_tickIsAtOrAboveLargest,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tickIsAtOrAboveLargest",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  nextInitializedTick(
    input: QueryInputs.Input_nextInitializedTick,
  ): ExtensionInvocation<Tick> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "nextInitializedTick",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Tick>(options),
    };
  }

  tickListIsSorted(
    input: QueryInputs.Input_tickListIsSorted,
  ): ExtensionInvocation<Boolean> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "tickListIsSorted",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Boolean>(options),
    };
  }

  getSqrtRatioAtTick(
    input: QueryInputs.Input_getSqrtRatioAtTick,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getSqrtRatioAtTick",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  getTickAtSqrtRatio(
    input: QueryInputs.Input_getTickAtSqrtRatio,
  ): ExtensionInvocation<Int32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getTickAtSqrtRatio",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Int32>(options),
    };
  }

  fetchToken(
    input: QueryInputs.Input_fetchToken,
  ): ExtensionInvocation<Token> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "fetchToken",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Token>(options),
    };
  }

  fetchPoolFromTokens(
    input: QueryInputs.Input_fetchPoolFromTokens,
  ): ExtensionInvocation<Pool> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "fetchPoolFromTokens",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Pool>(options),
    };
  }

  fetchPoolFromAddress(
    input: QueryInputs.Input_fetchPoolFromAddress,
  ): ExtensionInvocation<Pool> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "fetchPoolFromAddress",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Pool>(options),
    };
  }

  fetchTickList(
    input: QueryInputs.Input_fetchTickList,
  ): ExtensionInvocation<Array<Tick>> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "fetchTickList",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Array<Tick>>(options),
    };
  }

  feeAmountToTickSpacing(
    input: QueryInputs.Input_feeAmountToTickSpacing,
  ): ExtensionInvocation<Int32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "feeAmountToTickSpacing",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Int32>(options),
    };
  }

  getFeeAmount(
    input: QueryInputs.Input_getFeeAmount,
  ): ExtensionInvocation<UInt32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getFeeAmount",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<UInt32>(options),
    };
  }

  getPermitV(
    input: QueryInputs.Input_getPermitV,
  ): ExtensionInvocation<Int32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "getPermitV",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Int32>(options),
    };
  }

  FACTORY_ADDRESS(
    input: QueryInputs.Input_FACTORY_ADDRESS,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "FACTORY_ADDRESS",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  POOL_INIT_CODE_HASH(
    input: QueryInputs.Input_POOL_INIT_CODE_HASH,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "POOL_INIT_CODE_HASH",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  POOL_INIT_CODE_HASH_OPTIMISM(
    input: QueryInputs.Input_POOL_INIT_CODE_HASH_OPTIMISM,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "POOL_INIT_CODE_HASH_OPTIMISM",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  POOL_INIT_CODE_HASH_OPTIMISM_KOVAN(
    input: QueryInputs.Input_POOL_INIT_CODE_HASH_OPTIMISM_KOVAN,
  ): ExtensionInvocation<String> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "POOL_INIT_CODE_HASH_OPTIMISM_KOVAN",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<String>(options),
    };
  }

  MIN_TICK(
    input: QueryInputs.Input_MIN_TICK,
  ): ExtensionInvocation<Int32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "MIN_TICK",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Int32>(options),
    };
  }

  MAX_TICK(
    input: QueryInputs.Input_MAX_TICK,
  ): ExtensionInvocation<Int32> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "MAX_TICK",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<Int32>(options),
    };
  }

  MIN_SQRT_RATIO(
    input: QueryInputs.Input_MIN_SQRT_RATIO,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "MIN_SQRT_RATIO",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

  MAX_SQRT_RATIO(
    input: QueryInputs.Input_MAX_SQRT_RATIO,
  ): ExtensionInvocation<BigInt> {
    const options: InvokeApiOptions = {
      uri: this.uri.toString(),
      module: "query",
      method: "MAX_SQRT_RATIO",
      input: input
    };
    return {
      config: () => options,
      execute: async () => this.client.invoke<BigInt>(options),
    };
  }

}

export const uniswapExtension: ExtensionFactory<UniswapExtensionConfig> = (
  opts: UniswapExtensionConfig
) => {
  return {
    factory: (client: Client) => new UniswapExtension(client, opts),
    namespace: `uniswap`
  };
};
